### ISSUE TITLE
Crash when multiples windows are opened

### ISSUE THREAD

**Issue by Grum999** [Grum999/BuliNotes#1]
From https://krita-artists.org/t/buli-notes/20504/77

Encountered a new error:
1. create a new document
2. window-New window

Result: 
```
AttributeError
Python 3.8.1: C:\GAMES\STEAM\steamapps\common\Krita\krita\bin\krita.exe
Sun Jun  5 12:49:38 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\123\AppData\Roaming\krita\pykrita\bulinotes\bulinotes.py in canvasChanged(self=<bulinotes.bulinotes.BuliNotesDocker object>, canvas=<PyKrita.krita.Canvas object>)
   98 
   99     def canvasChanged(self, canvas):
  100         """Notify when views are added or removed"""
  101         if self.__ui:
  102             self.__ui.canvasChanged(canvas)
self = <bulinotes.bulinotes.BuliNotesDocker object>
self.__ui undefined
canvas = <PyKrita.krita.Canvas object>

 C:\Users\123\AppData\Roaming\krita\pykrita\bulinotes\bn\bnuidocker.py in canvasChanged(self=<bulinotes.bn.bnuidocker.BNUiDocker object>, canvas=<PyKrita.krita.Canvas object>)
  143         if canvas and Krita.instance().activeDocument():
  144             # memorize current document
  145             self.__kraActiveDocument=canvas.view().document()
  146         else:
  147             # no canvas means no document opened
self = <bulinotes.bn.bnuidocker.BNUiDocker object>
self.__kraActiveDocument undefined
canvas = <PyKrita.krita.Canvas object>
canvas.view = <built-in method view of Canvas object>
).document undefined
AttributeError: 'NoneType' object has no attribute 'document'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("'NoneType' object has no attribute 'document'",)
    with_traceback = <built-in method with_traceback of AttributeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\123\AppData\Roaming\krita\pykrita\bulinotes\bulinotes.py", line 102, in canvasChanged
    self.__ui.canvasChanged(canvas)
  File "C:\Users\123\AppData\Roaming\krita\pykrita\bulinotes\bn\bnuidocker.py", line 145, in canvasChanged
    self.__kraActiveDocument=canvas.view().document()
AttributeError: 'NoneType' object has no attribute 'document'
```

**Comment by Grum999** [comment]
Will be closed with release #1.0.0
