### ISSUE TITLE
Exception on startup

### ISSUE THREAD

**Issue by Grum999** [Grum999/BuliNotes#2]
From KA forum: https://krita-artists.org/t/buli-notes/20504/86?u=grum999

On MacOS, a python exception is raised on startup

```text
AttributeError
Python 3.9.12: /Users/sydni/Desktop/krita.app/Contents/MacOS/krita
Thu Sep 29 11:51:32 2022

A problem occurred in a Python script. Here is the sequence of
function calls leading up to the error, in the order they occurred.

/Users/sydni/Desktop/krita.app/Contents/Frameworks/krita-python-libs/krita/dockwidgetfactory.py in createDockWidget(self=<krita.dockwidgetfactory.DockWidgetFactory object>)
14 super(DockWidgetFactory, self).init(_id, _dockPosition)
15 self.klass = _klass
16
17 def createDockWidget(self):
18 return self.klass()
self = <krita.dockwidgetfactory.DockWidgetFactory object>
self.klass = <class ‘bulinotes.bulinotes.BuliNotesDocker’>

/Users/sydni/Library/Application Support/krita/pykrita/bulinotes/bulinotes.py in init(self=<bulinotes.bulinotes.BuliNotesDocker object>)
92 self.setWindowTitle(PLUGIN_MENU_ENTRY)
93 if checkKritaVersion(*REQUIRED_KRITA_VERSION):
94 self.__ui=BNUiDocker(self, PLUGIN_MENU_ENTRY, EXTENSION_ID, PLUGIN_VERSION)
95 self.setWidget(self.__ui)
96 else:
self = <bulinotes.bulinotes.BuliNotesDocker object>
self.__ui undefined
global BNUiDocker = <class ‘bulinotes.bn.bnuidocker.BNUiDocker’>
global PLUGIN_MENU_ENTRY = ‘Buli Notes’
global EXTENSION_ID = ‘pykrita_bulinotes’
global PLUGIN_VERSION = ‘0.4.0b’

 /Users/sydni/Library/Application Support/krita/pykrita/bulinotes/bn/bnuidocker.py in __init__(self=<bulinotes.bn.bnuidocker.BNUiDocker object>, docker=<bulinotes.bulinotes.BuliNotesDocker object>, bnName='Buli Notes', bnId='pykrita_bulinotes', bnVersion='0.4.0b', parent=None)
   61 
   62         uiFileName = os.path.join(os.path.dirname(__file__), 'resources', 'bnuidocker.ui')
   63         loadXmlUi(uiFileName, self)
   64 
   65         self.__initialize()
global loadXmlUi = <function loadXmlUi>
uiFileName = '/Users/sydni/Library/Application Support/krita/pykrita/bulinotes/bn/resources/bnuidocker.ui'
self = <bulinotes.bn.bnuidocker.BNUiDocker object>

 /Users/sydni/Library/Application Support/krita/pykrita/bulinotes/pktk/modules/utils.py in loadXmlUi(fileName='/Users/sydni/Library/Application Support/krita/pykrita/bulinotes/bn/resources/bnuidocker.ui', parent=<bulinotes.bn.bnuidocker.BNUiDocker object>)
  198     # Parse XML file and retrieve all object for which an icon is set
  199     tree = ET.parse(fileName)
  200     for nodeParent in tree.getiterator():
  201         for nodeChild in nodeParent:
  202             if 'name' in nodeChild.attrib and nodeChild.attrib['name'] == 'icon':
nodeParent undefined
tree = <xml.etree.ElementTree.ElementTree object>
tree.getiterator undefined
AttributeError: 'ElementTree' object has no attribute 'getiterator'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("'ElementTree' object has no attribute 'getiterator'",)
    with_traceback = <built-in method with_traceback of AttributeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/Users/sydni/Desktop/krita.app/Contents/Frameworks/krita-python-libs/krita/dockwidgetfactory.py", line 18, in createDockWidget
    return self.klass()
  File "/Users/sydni/Library/Application Support/krita/pykrita/bulinotes/bulinotes.py", line 94, in __init__
    self.__ui=BNUiDocker(self, PLUGIN_MENU_ENTRY, EXTENSION_ID, PLUGIN_VERSION)
  File "/Users/sydni/Library/Application Support/krita/pykrita/bulinotes/bn/bnuidocker.py", line 63, in __init__
    loadXmlUi(uiFileName, self)
  File "/Users/sydni/Library/Application Support/krita/pykrita/bulinotes/pktk/modules/utils.py", line 200, in loadXmlUi
    for nodeParent in tree.getiterator():
AttributeError: 'ElementTree' object has no attribute 'getiterator'
```

The problem occurs when ui file is loaded, possible case for origin of problem:
- The file is corrupted and can't be loaded
- Python version here is 3.9.12 and bundled python version in appimage is 3.8.1; may be for this version of python something doesn't work like with version 3.8 with XML parser

**Comment by Grum999** [comment]
Confirmed that python version 3.9.12 is origin of problem

For `xml.etree.ElementTree`, on python 3.8 console, use of `getiterator()` method return the following warning:
```
<stdin>:1: DeprecationWarning: This method will be removed in future versions.  Use 'tree.iter()' or 'list(tree.iter())' instead.
```

Then just have to use `iter()` instead of `getiterator()`

**Comment by Grum999** [comment]
Will be close with release #1.0.0
