### ISSUE TITLE
Creating a note

### ISSUE THREAD

**Issue by EyeOdin** [Grum999/BuliNotes#7]
I am on windows and when I hit add note this message pops up.
```
KeyError
Python 3.8.1: C:\Program Files\Krita (x64)\bin\krita.exe
Mon Apr  3 15:14:14 2023

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\EyeOd\AppData\Roaming\krita\pykrita\bulinotes\bn\bnuidocker.py in __addNote(self=<bulinotes.bn.bnuidocker.BNUiDocker object>)
   88     def __addNote(self):
   89         """Add a new note in notes"""
   90         note=BNNoteEditor.edit(BNNote())
   91         if note:
   92             note.setPosition(self.__notes.length())
note undefined
global BNNoteEditor = <class 'bulinotes.bn.bnnotes.BNNoteEditor'>
BNNoteEditor.edit = <function BNNoteEditor.edit>
global BNNote = <class 'bulinotes.bn.bnnotes.BNNote'>

 C:\Users\EyeOd\AppData\Roaming\krita\pykrita\bulinotes\bn\bnnotes.py in edit(note=<BNNote({8e95239e-023c-425d-b2c8-0950de520125}, None, False, False, False)>)
 1019     def edit(note):
 1020         """Open a dialog box to edit note"""
 1021         dlgBox = BNNoteEditor(note)
 1022 
 1023         returned = dlgBox.exec()
dlgBox undefined
global BNNoteEditor = <class 'bulinotes.bn.bnnotes.BNNoteEditor'>
note = <BNNote({8e95239e-023c-425d-b2c8-0950de520125}, None, False, False, False)>

 C:\Users\EyeOd\AppData\Roaming\krita\pykrita\bulinotes\bn\bnnotes.py in __init__(self=<bulinotes.bn.bnnotes.BNNoteEditor object>, note=<BNNote({8e95239e-023c-425d-b2c8-0950de520125}, None, False, False, False)>, name='Buli Notes', parent=None)
 1066 
 1067         self.__saveViewConfig()
 1068         self.__buildUi()
 1069         self.__initViewConfig()
 1070 
self = <bulinotes.bn.bnnotes.BNNoteEditor object>
self.__buildUi undefined

 C:\Users\EyeOd\AppData\Roaming\krita\pykrita\bulinotes\bn\bnnotes.py in __buildUi(self=<bulinotes.bn.bnnotes.BNNoteEditor object>)
 1124 
 1125 
 1126         self.__actionSelectDefaultBrush=QAction(QIcon(QPixmap.fromImage(self.__allBrushesPreset['b)_Basic-5_Size'].image())), i18n('Default note brush'), self)
 1127         self.__actionSelectDefaultBrush.triggered.connect(self.__actionScratchpadSetBrushDefault)
 1128         self.__actionSelectCurrentBrush=QAction(QIcon(QPixmap.fromImage(self.__activeViewCurrentConfig['brushPreset'].image())), i18n(f"Current painting brush ({self.__activeViewCurrentConfig['brushPreset'].name()})"), self)
self = <bulinotes.bn.bnnotes.BNNoteEditor object>
self.__actionSelectDefaultBrush undefined
global QAction = <class 'PyQt5.QtWidgets.QAction'>
global QIcon = <class 'PyQt5.QtGui.QIcon'>
global QPixmap = <class 'PyQt5.QtGui.QPixmap'>
QPixmap.fromImage = <built-in function fromImage>
self.__allBrushesPreset undefined
builtini18n = <built-in function krita_i18n>
KeyError: 'b)_Basic-5_Size'
    __cause__ = None
    __class__ = <class 'KeyError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of KeyError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of KeyError object>
    __doc__ = 'Mapping key not found.'
    __eq__ = <method-wrapper '__eq__' of KeyError object>
    __format__ = <built-in method __format__ of KeyError object>
    __ge__ = <method-wrapper '__ge__' of KeyError object>
    __getattribute__ = <method-wrapper '__getattribute__' of KeyError object>
    __gt__ = <method-wrapper '__gt__' of KeyError object>
    __hash__ = <method-wrapper '__hash__' of KeyError object>
    __init__ = <method-wrapper '__init__' of KeyError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of KeyError object>
    __lt__ = <method-wrapper '__lt__' of KeyError object>
    __ne__ = <method-wrapper '__ne__' of KeyError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of KeyError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of KeyError object>
    __repr__ = <method-wrapper '__repr__' of KeyError object>
    __setattr__ = <method-wrapper '__setattr__' of KeyError object>
    __setstate__ = <built-in method __setstate__ of KeyError object>
    __sizeof__ = <built-in method __sizeof__ of KeyError object>
    __str__ = <method-wrapper '__str__' of KeyError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ('b)_Basic-5_Size',)
    with_traceback = <built-in method with_traceback of KeyError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\EyeOd\AppData\Roaming\krita\pykrita\bulinotes\bn\bnuidocker.py", line 90, in __addNote
    note=BNNoteEditor.edit(BNNote())
  File "C:\Users\EyeOd\AppData\Roaming\krita\pykrita\bulinotes\bn\bnnotes.py", line 1021, in edit
    dlgBox = BNNoteEditor(note)
  File "C:\Users\EyeOd\AppData\Roaming\krita\pykrita\bulinotes\bn\bnnotes.py", line 1068, in __init__
    self.__buildUi()
  File "C:\Users\EyeOd\AppData\Roaming\krita\pykrita\bulinotes\bn\bnnotes.py", line 1126, in __buildUi
    self.__actionSelectDefaultBrush=QAction(QIcon(QPixmap.fromImage(self.__allBrushesPreset['b)_Basic-5_Size'].image())), i18n('Default note brush'), self)
KeyError: 'b)_Basic-5_Size'
```

**Comment by Grum999** [comment]
Hi

Which version of BuliNotes are you using?
Which version of Krita are you using?

From v0.4.0b, this has normally been fixed:
https://github.com/Grum999/BuliNotes/blob/a7a12d1fbab4fa9f29cec2a1e016e20b5cb0ea64/releases-notes/RELEASE-0.4.0b.md?plain=1#L26-L29


So, having a reference to a brush **b)_Basic-5_Size** is weird; for now I can see 2 possible case:
- Running an outdated version of Krita? 
- Running an outdated version of plugin BuliNotes?
  - I can see this in log
    `File "C:\Users\EyeOd\AppData\Roaming\krita\pykrita\bulinotes\bn\bnnotes.py", line 1126, in __buildUi` 
    The line in error doesn't exist anymore in last version of plugin, and has been replaced by this one:
    https://github.com/Grum999/BuliNotes/blob/a7a12d1fbab4fa9f29cec2a1e016e20b5cb0ea64/bulinotes/bulinotes/bn/bnnotes.py#L1509
    

Can you check your version, and if not the last one, install the last one and check if problem still occurs?


Grum999

**Comment by EyeOdin** [comment]
it seems I had a really old version installed and not the new one I had downloaded. I updated again and it is working now.

thank you
